<?php
/**
 * Create bounded GitHub issue reports from MCP clients.
 *
 * @package Aculect\AICompanion\Connectors\MCP
 */

declare(strict_types=1);

namespace Aculect\AICompanion\Connectors\MCP;

/**
 * Prepares public plugin issue reports without storing secrets.
 */
final class PluginIssueReporter {

	private const DEFAULT_REPOSITORY = 'mehul0810/aculect-ai-companion';
	private const MAX_TITLE_LENGTH   = 120;
	private const MAX_FIELD_LENGTH   = 2000;
	private const MAX_BODY_LENGTH    = 60000;

	/**
	 * Create the reporter.
	 *
	 * @param string|null $repository Optional owner/repo override for tests.
	 */
	public function __construct(
		private readonly ?string $repository = null
	) {}

	/**
	 * Prepare a GitHub issue from an MCP client report.
	 *
	 * @param array<string, mixed> $args   Tool arguments.
	 * @param array<string, mixed> $source Authenticated MCP connection context.
	 * @return array<string, mixed>
	 */
	public function report( array $args, array $source = array() ): array {
		$title   = $this->sanitize_single_line( $args['title'] ?? '', self::MAX_TITLE_LENGTH );
		$summary = $this->sanitize_multiline( $args['summary'] ?? $args['issue'] ?? '', self::MAX_FIELD_LENGTH );

		if ( '' === $title && '' !== $summary ) {
			$title = $this->sanitize_single_line( $summary, self::MAX_TITLE_LENGTH );
		}

		if ( '' === $title || '' === $summary ) {
			return array(
				'status'  => 'rejected',
				'error'   => 'title_and_summary_required',
				'message' => 'Plugin issue reports require a title and summary.',
			);
		}

		$repository = $this->repository();
		if ( '' === $repository ) {
			return array(
				'status'  => 'configuration_required',
				'error'   => 'invalid_github_repository',
				'message' => 'The configured GitHub repository is invalid. Expected owner/repository.',
			);
		}

		$body = $this->issue_body( $args, $source, $summary );

		return array(
			'status'            => 'ready_for_client_submission',
			'message'           => 'Plugin issue report prepared. Create the issue in the public GitHub repository if the client has GitHub tools available, or share the prefilled issue URL with the user.',
			'repository'        => $repository,
			'title'             => $title,
			'body'              => $body,
			'issue_url'         => $this->manual_issue_url( $repository, $title, $body ),
			'can_create_direct' => false,
			'next_actions'      => array(
				'If this assistant has a GitHub connector or GitHub CLI access, create a new issue in the returned repository using the returned title and body.',
				'If no GitHub tool is available, give the user the prefilled issue_url.',
				'Do not add secrets, credentials, OAuth tokens, raw tool arguments, or private site settings to the public issue.',
			),
		);
	}

	/**
	 * Return the configured GitHub repository.
	 */
	private function repository(): string {
		$repository = null !== $this->repository ? $this->repository : self::DEFAULT_REPOSITORY;
		$repository = (string) apply_filters( 'aculect_ai_companion_github_issue_reporter_repository', $repository );
		$repository = trim( $repository );

		return preg_match( '/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/', $repository ) ? $repository : '';
	}

	/**
	 * Build a public, redacted GitHub issue body.
	 *
	 * @param array<string, mixed> $args    Tool arguments.
	 * @param array<string, mixed> $source  Authenticated MCP connection context.
	 * @param string               $summary Sanitized summary.
	 */
	private function issue_body( array $args, array $source, string $summary ): string {
		$sections = array(
			'## Summary' . "\n" . $summary,
			'## Context' . "\n" . $this->context_markdown( $args, $source ),
		);

		$steps = $this->string_list( $args['steps_to_reproduce'] ?? array(), 8 );
		if ( array() !== $steps ) {
			$sections[] = '## Steps to reproduce' . "\n" . implode(
				"\n",
				array_map(
					static fn( int $index, string $step ): string => ( $index + 1 ) . '. ' . $step,
					array_keys( $steps ),
					$steps
				)
			);
		}

		foreach (
			array(
				'expected_behavior' => 'Expected behavior',
				'actual_behavior'   => 'Actual behavior',
				'evidence'          => 'Non-sensitive evidence',
			) as $key => $label
		) {
			$value = $this->sanitize_multiline( $args[ $key ] ?? '', self::MAX_FIELD_LENGTH );
			if ( '' !== $value ) {
				$sections[] = '## ' . $label . "\n" . $value;
			}
		}

		$sections[] = '## Safety' . "\n" . 'Generated by the Aculect AI Companion MCP issue reporter. The report intentionally excludes secrets, credentials, raw OAuth tokens, raw tool arguments, and full private site settings.';

		return substr( implode( "\n\n", $sections ), 0, self::MAX_BODY_LENGTH );
	}

	/**
	 * Build safe context markdown.
	 *
	 * @param array<string, mixed> $args   Tool arguments.
	 * @param array<string, mixed> $source Authenticated MCP connection context.
	 */
	private function context_markdown( array $args, array $source ): string {
		$home_host = '';
		if ( function_exists( 'home_url' ) ) {
			$home_host = (string) wp_parse_url( home_url( '/' ), PHP_URL_HOST );
		}

		$lines = array(
			'- Client: ' . $this->sanitize_single_line( $args['client_name'] ?? $source['client_name'] ?? $source['provider'] ?? 'MCP client', 100 ),
			'- Provider: ' . $this->sanitize_single_line( $source['provider'] ?? $args['provider'] ?? '', 80 ),
			'- Workflow: ' . $this->sanitize_single_line( $args['workflow'] ?? '', 120 ),
			'- Tool: ' . $this->sanitize_single_line( $args['tool_name'] ?? '', 120 ),
			'- Severity: ' . sanitize_key( (string) ( $args['severity'] ?? 'bug' ) ),
			'- Site host: ' . $this->sanitize_single_line( $home_host, 120 ),
			'- Plugin version: ' . ACULECT_AI_COMPANION_VERSION,
			'- WordPress version: ' . ( function_exists( 'get_bloginfo' ) ? $this->sanitize_single_line( get_bloginfo( 'version' ), 30 ) : '' ),
			'- PHP version: ' . PHP_VERSION,
			'- Environment: ' . ( function_exists( 'wp_get_environment_type' ) ? sanitize_key( wp_get_environment_type() ) : 'production' ),
		);

		return implode( "\n", array_filter( $lines, static fn( string $line ): bool => ! str_ends_with( $line, ': ' ) ) );
	}

	/**
	 * Return a manual issue URL when API creation is not configured.
	 *
	 * @param string $repository Repository in owner/name format.
	 * @param string $title      Public issue title.
	 * @param string $body       Public issue body.
	 */
	private function manual_issue_url( string $repository, string $title, string $body ): string {
		return esc_url_raw(
			add_query_arg(
				array(
					'title' => $title,
					'body'  => substr( $body, 0, 4000 ),
				),
				'https://github.com/' . $repository . '/issues/new'
			)
		);
	}

	/**
	 * Sanitize a single-line field.
	 *
	 * @param mixed $value      Raw field value.
	 * @param int   $max_length Maximum returned length.
	 */
	private function sanitize_single_line( mixed $value, int $max_length ): string {
		$value = is_scalar( $value ) ? sanitize_text_field( (string) $value ) : '';

		return substr( $value, 0, $max_length );
	}

	/**
	 * Sanitize a multi-line field.
	 *
	 * @param mixed $value      Raw field value.
	 * @param int   $max_length Maximum returned length.
	 */
	private function sanitize_multiline( mixed $value, int $max_length ): string {
		if ( ! is_scalar( $value ) ) {
			return '';
		}

		$value = (string) $value;
		$value = function_exists( 'sanitize_textarea_field' ) ? sanitize_textarea_field( $value ) : sanitize_text_field( $value );

		return substr( $value, 0, $max_length );
	}

	/**
	 * Sanitize a bounded string list.
	 *
	 * @param mixed $value Raw list.
	 * @param int   $limit Maximum number of returned items.
	 * @return list<string>
	 */
	private function string_list( mixed $value, int $limit ): array {
		if ( ! is_array( $value ) ) {
			return array();
		}

		$items = array();
		foreach ( $value as $item ) {
			$item = $this->sanitize_multiline( $item, 500 );
			if ( '' !== $item ) {
				$items[] = $item;
			}

			if ( count( $items ) >= $limit ) {
				break;
			}
		}

		return $items;
	}
}
